/**
 * Framework adapters — the "Automated Production Handoff" the Ship step was
 * missing (previously: Figma JSON + a markdown doc, nothing runnable). Pure
 * transforms off the same token state `lib/tokens.ts` already compiles for
 * every preview frame; no new dependency, no Style Dictionary build step.
 */
import type { ArkitypeState, PreviewMode } from "@/store/useDesignSystem";
import { RADII_NAMES } from "@/store/useDesignSystem";
import { rampStepLabels } from "@/lib/color";
import { resolveToken, systemCssVars } from "@/lib/tokens";
import { generateTypeScale, STEP_DEFS } from "@/lib/typography";

type TokenState = Pick<ArkitypeState, "primitives" | "semantics">;

const cssBlock = (vars: Record<string, string>, indent = "  "): string =>
  Object.entries(vars)
    .map(([k, v]) => `${indent}${k}: ${v};`)
    .join("\n");

/** A real, drop-in CSS custom-properties file — the one export format that
 *  didn't exist at all before (Ship step only offered Figma JSON + docs). */
export function compileCssVariables(state: TokenState): string {
  const light = systemCssVars(state, "light") as Record<string, string>;
  const dark = systemCssVars(state, "dark") as Record<string, string>;
  return [
    "/* Generated by Arkitype — design tokens as CSS custom properties. */",
    "/* Toggle dark mode by adding/removing the .dark class on <html>/<body>. */",
    "",
    ":root {",
    cssBlock(light),
    "}",
    "",
    ".dark {",
    cssBlock(dark),
    "}",
    "",
  ].join("\n");
}

function typeSteps(t: ArkitypeState["primitives"]["typography"]) {
  return generateTypeScale(
    t.baseSize,
    t.scaleFactor,
    {
      rounding: t.rounding,
      sizeOverrides: t.sizeOverrides,
      leadingOverrides: t.leadingOverrides,
      stepAssign: t.stepAssign,
    },
    t.stepDefs ?? STEP_DEFS
  );
}

/**
 * `tailwind.config.js` mapped onto the SAME `--ark-*` variables the CSS
 * export above defines — copy both files together (the config alone has no
 * colours to read from). This is the real pattern professional token
 * pipelines use for Tailwind + dark mode, not a baked-hex snapshot that goes
 * stale the next time a token changes.
 */
export function compileTailwindConfig(state: TokenState): string {
  const { primitives, semantics } = state;

  const semanticColors = Object.keys(semantics.modes.light)
    .sort()
    .map((k) => `        "${k}": "var(--ark-${k})",`)
    .join("\n");

  const familyBlocks = primitives.colorFamilies
    .map((f) => {
      const labels = rampStepLabels(f.steps);
      const steps = labels.map((label) => `          "${label}": "var(--ark-${f.id}-${label})",`).join("\n");
      return `        ${JSON.stringify(f.id)}: {\n${steps}\n        },`;
    })
    .join("\n");

  const spacing = primitives.spacing
    .map((_, i) => `        "${i + 1}": "var(--ark-space-${i + 1})",`)
    .join("\n");

  const radiusNames = primitives.radiusNames ?? [...RADII_NAMES];
  const radius = primitives.radii
    .map((_, i) => `        "${radiusNames[i] ?? `step-${i}`}": "var(--ark-radius-${radiusNames[i] ?? `step-${i}`})",`)
    .join("\n");

  const steps = typeSteps(primitives.typography);
  const fontSize = steps
    .map((s) => `        "${s.name}": ["var(--ark-text-${s.name})", { lineHeight: "var(--ark-leading-${s.name})" }],`)
    .join("\n");

  const fontWeight = primitives.typography.weights
    .map((w) => `        "${w.name}": "var(--ark-font-weight-${w.name})",`)
    .join("\n");

  const boxShadow = primitives.elevation.light
    .map((d) => `        "${d.name}": "var(--ark-shadow-${d.name})",`)
    .join("\n");

  const duration = Object.keys(primitives.motion.durations)
    .map((k) => `        "${k}": "var(--ark-duration-${k})",`)
    .join("\n");

  const easing = primitives.motion.easings
    .map((e) => `        "${e.name}": "var(--ark-ease-${e.name})",`)
    .join("\n");

  return `/**
 * Generated by Arkitype. Colours/scales resolve through the --ark-* CSS
 * custom properties — import the companion CSS variables export (:root +
 * .dark) alongside this file, or values render as unset.
 */
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
${semanticColors}
${familyBlocks}
      },
      spacing: {
${spacing}
      },
      borderRadius: {
${radius}
      },
      fontSize: {
${fontSize}
      },
      fontWeight: {
${fontWeight}
      },
      boxShadow: {
${boxShadow}
      },
      transitionDuration: {
${duration}
      },
      transitionTimingFunction: {
${easing}
      },
    },
  },
};
`;
}

/**
 * MUI `createTheme({...})` sources with fully resolved values (MUI doesn't
 * consume CSS custom properties for its own computations — contrast text,
 * tonal variants, etc. — the way Tailwind's utility classes can), one per
 * mode. Palette/spacing/shape/typography only: `shadows` is intentionally
 * left at MUI's default rather than emitting a wrong-length elevation array,
 * which would break at runtime.
 */
export function compileMuiTheme(state: TokenState): string {
  const { primitives, semantics } = state;
  const resolve = (mode: PreviewMode, token: string) => resolveToken(state, mode, token);

  const paletteFor = (mode: PreviewMode) => ({
    mode,
    primary: {
      main: resolve(mode, "action-primary-default"),
      light: resolve(mode, "action-primary-hover"),
      dark: resolve(mode, "action-primary-active"),
      contrastText: resolve(mode, "text-on-action"),
    },
    secondary: {
      main: resolve(mode, "action-secondary-default"),
      light: resolve(mode, "action-secondary-hover"),
      dark: resolve(mode, "action-secondary-active"),
      contrastText: resolve(mode, "text-primary"),
    },
    error: {
      main: resolve(mode, "feedback-error-text"),
      light: resolve(mode, "feedback-error-surface"),
      contrastText: resolve(mode, "text-on-action"),
    },
    warning: {
      main: resolve(mode, "feedback-warning-text"),
      light: resolve(mode, "feedback-warning-surface"),
      contrastText: resolve(mode, "text-on-action"),
    },
    info: {
      main: resolve(mode, "feedback-info-text"),
      light: resolve(mode, "feedback-info-surface"),
      contrastText: resolve(mode, "text-on-action"),
    },
    success: {
      main: resolve(mode, "feedback-success-text"),
      light: resolve(mode, "feedback-success-surface"),
      contrastText: resolve(mode, "text-on-action"),
    },
    background: {
      default: resolve(mode, "surface-base"),
      paper: resolve(mode, "surface-elevated"),
    },
    text: {
      primary: resolve(mode, "text-primary"),
      secondary: resolve(mode, "text-secondary"),
      disabled: resolve(mode, "action-primary-disabled"),
    },
    divider: resolve(mode, "border-default"),
  });

  const t = primitives.typography;
  const steps = typeSteps(t);
  const weightValue = (name?: string): number =>
    t.weights.find((w) => w.name === name)?.value ?? 400;
  const findStep = (name: string) => steps.find((s) => s.name === name);
  const body = findStep("base");
  const h1 = findStep("4xl");
  const h2 = findStep("3xl");
  const h3 = findStep("2xl");
  const h4 = findStep("xl");
  const caption = findStep("xs");

  const spacingUnit = primitives.spacing[0] ?? 4; // space-1, matches MUI's default 8px-multiplier convention
  const radiusNames = primitives.radiusNames ?? [...RADII_NAMES];
  const mdIdx = radiusNames.indexOf("md");
  const borderRadius = Math.round(primitives.radii[mdIdx >= 0 ? mdIdx : 3] ?? 8);
  const fontFamily = t.fontRoles.body?.family ?? "system-ui, sans-serif";

  const typography = `{
    fontFamily: ${JSON.stringify(fontFamily)},
    h1: { fontSize: "${h1?.size ?? 48}px", fontWeight: ${weightValue(h1?.weight)}, lineHeight: ${h1?.lineHeight ?? 1.15} },
    h2: { fontSize: "${h2?.size ?? 36}px", fontWeight: ${weightValue(h2?.weight)}, lineHeight: ${h2?.lineHeight ?? 1.2} },
    h3: { fontSize: "${h3?.size ?? 28}px", fontWeight: ${weightValue(h3?.weight)}, lineHeight: ${h3?.lineHeight ?? 1.25} },
    h4: { fontSize: "${h4?.size ?? 22}px", fontWeight: ${weightValue(h4?.weight)}, lineHeight: ${h4?.lineHeight ?? 1.3} },
    body1: { fontSize: "${body?.size ?? 16}px", fontWeight: ${weightValue(body?.weight)}, lineHeight: ${body?.lineHeight ?? 1.5} },
    caption: { fontSize: "${caption?.size ?? 12}px", fontWeight: ${weightValue(caption?.weight)}, lineHeight: ${caption?.lineHeight ?? 1.4} },
  }`;

  const themeFor = (mode: PreviewMode, exportName: string) => `export const ${exportName} = createTheme({
  palette: ${JSON.stringify(paletteFor(mode), null, 2)},
  spacing: ${spacingUnit},
  shape: { borderRadius: ${borderRadius} },
  typography: ${typography},
});`;

  return `/**
 * Generated by Arkitype — MUI theme objects with fully resolved values.
 * npm i @mui/material @emotion/react @emotion/styled
 */
import { createTheme } from "@mui/material/styles";

${themeFor("light", "arkitypeLightTheme")}

${themeFor("dark", "arkitypeDarkTheme")}
`;
}
